### ISSUE TITLE
Directions to run source code? Development workflow?

### ISSUE THREAD

**Issue by swork1** [JasonSteving99/claro-lang#49]
I was poking around in the source code and was trying to figure out how to run the compiler code given a `.claro` file. I am able to get an output file using a command like `bazel-bin/bootstrapping_claro_compiler_binary --java_source --package com.swork.test --src /home/swork1/claro-lang-swork1/test.claro --classname Test --output_file_path src/java/com/swork/test/Test.java`

The issue is I can't just run this `.java` file without the dependencies, how can I link the dependencies correctly? How you go about your development workflow in general? Is there a README I may be failing to find?

I've never used bazel before (spent a couple hours messing around now) so maybe I'm just missing something obvious here. Thanks!

**Comment by JasonSteving99** [comment]
Hi! Thanks for giving Claro a try! I recommend working through the [Getting Started](https://docs.clarolang.com/getting_started/getting_started.html) guide. You should be working with commands like `bazel build` and `bazel run` to work with Claro programs. I actually don't intend to ever provide (first party) support for working with the Claro compiler directly.

**Comment by swork1** [comment]
> Hi! Thanks for giving Claro a try! I recommend working through the [Getting Started](https://docs.clarolang.com/getting_started/getting_started.html) guide. You should be working with commands like `bazel build` and `bazel run` to work with Claro programs. I actually don't intend to ever provide (first party) support for working with the Claro compiler directly.

Yea I have Claro working fine. I was curious of working with the Claro compiler directly if possible. But I guess if you don't support that I can't.

**Comment by JasonSteving99** [comment]
Ahh I see :). Ya the thing is that Claro's dependency management story is very different than that of other languages. It's tailored to work well in a Bazel context, but this becomes really difficult to work with when you have to invoke the compiler manually. Basically the key here is that `.claro` source files don't have any such thing as an `import` statement, deps are listed in BUILD files. This means that if you had to interact with the compiler yourself you'd have to add a new command line flag for every dep manually. Even worse, you'd have to manually compile modules in the correct order as currently Bazel owns that responsibility (I guess Make could handle this ordering for you, but then why not use Bazel?).

These seem super untenable without something like Bazel orchestrating. Does that reasoning make sense?

**Comment by swork1** [comment]
I think that makes sense. So there is not a straightforward way of making some changes and re-building the compiler to test them out? A lot of the dependencies/tasks are hidden away in the `claro-lang` bazel_dep?

That's kind of a bummer as I was planning on poking around in the compiler and build/test different things and understand how some things are implemented.

**Comment by JasonSteving99** [comment]
Ahhh I see, so you want to know how to actually _modify_ the compiler itself - cool! In that case, your best bet is gonna be to instead clone the repo. Once you clone the repo you'll still be able to use the exact same steps for building/running Claro programs as in the Getting Started guide, but you'll also have access to modifying the compiler source. As long as your `claro_binary()` and `claro_module()` targets are defined within the Bazel workspace of the _cloned_ repo, you'll just automatically be building against your locally modified version.

I'll be interested to see what sorts of experiments you get up to! And I'm happy to help.

**Comment by swork1** [comment]
Ah that makes much more sense now b/c `claro-lang` is defined in the root MODULE.bazel. I can see that bazel is using the source files now to build. Thank you!

Last question (well maybe lol). Is there a way to see debug (java print statements) output when building?

**Comment by JasonSteving99** [comment]
For sure! And ya, for general usage, putting `bazel_dep(name = "claro-lang", version = "...")` in your MODULE.bazel is remotely fetching Claro from the Bazel Central Registry and then building it from source, but of course you don't have direct access to the source files itself this way.

And ya, you should be able to see java print statements if you just add them to the compiler source files somewhere that actually runs, I frequently print to stderr for debugging. The only other thing you might want to know about is that you can see stack traces to see the origin of various things that end up producing compiler errors (like type mismatches). Just use `debug = True` in your `claro_binary(..., debug = True)` or `claro_module(..., debug = True)` target definitions.

**Comment by swork1** [comment]
Awesome thank you!
