### ISSUE TITLE
HttpService parsing issue

### ISSUE THREAD

**Issue by swork1** [JasonSteving99/claro-lang#50]
Compiler throws a syntax error when compiling the following example. The output error is misleading and doesn't point out that there is a trailing `,` in the `HttpService` definition.

Example
```
HttpService Server {
  rootEndpoint: "/",
}

endpoint_handlers Server {
  graph provider rootEndpoint() -> future<HttpResponse> {
    root res <- http::getOk200HttpResponseForHtml(@formattedHtml);
    node formattedHtml <- futures::immediateFuture("");
  }
}

var server: HttpServer<Server> = http::getBasicHttpServerForPort(8080);
http::startServerAndAwaitShutdown(server);
```

The compiler works fine if you remove the trailing `,` like so
```
HttpService Server {
  rootEndpoint: "/",
}
```

I attempted to look into `ClaroParser.cup` but I'm not familiar enough with how to possibly handle generating a more specific error message for `http_endpoints_list`. Curious as to what the solution would be!

**Comment by swork1** [comment]
I took some time and looked into it some more. You can get more accurate error positioning with the PR I opened up. Hopefully that is at least in the right direction

**Comment by JasonSteving99** [comment]
Thanks for making this change! Btw, there're probably several places where this type of thing actually comes up (for example, would also come up with structs). So, realistically what I'd really want long term is for a more holistic solution to better parsing-related error messaging.

My intention is to eventually switch entirely from JCup to ANTLR as the parser generator. I think using JCup at all was a significant mistake. There would be countless benefits of using ANTLR instead, but one that's relevant to this conversation is the fact that this sort of error messaging is just already baked in by default. So, I probably won't be investing all that much in hunting down too many incremental improvements to parsing in this current JCup world. Rather, I'd hope to get a big bang improvement once I can migrate to ANTLR.

**Comment by swork1** [comment]
Awesome, sounds like switching to ANTLR would be the way to go then. Good luck!
